In [1]:
import numpy as np
arr=np.array([10,20,30])

In [2]:
arr

array([10, 20, 30])

In [3]:
type(arr)

numpy.ndarray

In [7]:
arr1=np.array([[1,2,3],[2,3,4]])

In [8]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [12]:
arr=np.zeros(3,dtype=int)
arr

array([0, 0, 0])

In [15]:
arr=np.ones(2)
arr

array([1., 1.])

In [16]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [18]:
arr.shape

(5,)

In [19]:
arr=np.arange(2,9,2)
arr

array([2, 4, 6, 8])

In [20]:
arr=np.linspace(0,10,5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
arr.reshape(5,2)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [11,12,13]])
arr

/home/tanka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  This is separate from the ipykernel package so we can avoid doing imports until


array([list([1, 2, 3, 4]), list([5, 6, 7, 8]), list([11, 12, 13])],
      dtype=object)

In [27]:
arr

array([list([1, 2, 3, 4]), list([5, 6, 7, 8]), list([11, 12, 13])],
      dtype=object)

In [28]:
arr.ndim

1

In [29]:
arr.shape

(3,)

In [35]:
arr=np.array([[1,2,3],[3,4,5]])

In [36]:
arr.ndim

2

In [37]:
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [38]:
arr[1][1]

4

In [39]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [40]:
arr.ndim

2

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [45]:
mar=np.matrix("1 3;3 4")
mar

matrix([[1, 3],
        [3, 4]])

In [46]:
type(mar)

numpy.matrix

In [49]:
mar.max(axis=0)

matrix([[3, 4]])

In [48]:
mar.max(axis=1)

matrix([[3],
        [4]])